// src/constants/hospitals.js

export const HOSPITALS_BY_REGION = {
  'Ashanti': [
    'Komfo Anokye Teaching Hospital',
    'Manhyia District Hospital',
    'Tafo Government Hospital',
    'Suntreso Government Hospital',
    'Ejisu Government Hospital',
    'Bekwai Municipal Hospital',
    'Agogo Presbyterian Hospital',
    'Mampong Government Hospital',
    'Juaso Government Hospital',
    'Obuasi Government Hospital',
    'Fomena Government Hospital',
    'Kumasi South Hospital',
    'University Hospital, KNUST',
    'St. Martin\'s Hospital (Agogo)',
  ],
  'Greater Accra': [
    'Korle Bu Teaching Hospital',
    'Ridge Hospital',
    'La General Hospital',
    'Tema General Hospital',
    'Legon Hospital',
    'Achimota Hospital',
    'Madina Polyclinic',
    'Nsawam Government Hospital',
    'Dodowa Hospital',
    'Ashaiman Municipal Hospital',
    '37 Military Hospital',
    'Police Hospital',
    'LEKMA Hospital',
    'Princess Marie Louise Hospital',
    'Nyaho Medical Centre',
    'Lister Hospital',
    'The Gallery Hospital',
    'Trust Hospital',
  ],
  'Western': [
    'Effia-Nkwanta Regional Hospital',
    'Sekondi-Takoradi Government Hospital',
    'Tarkwa Government Hospital',
    'Efuraman Hospital',
    'Wasa Akropong Hospital',
    'Essikado Government Hospital',
    'Bogoso Government Hospital',
    'Shama Government Hospital',
    'Prestea Government Hospital',
    'Axim Government Hospital',
    'Nkroful Hospital',
    'St. John of God Hospital (Eshiem)',
    'Enchi Government Hospital',
  ],
  'Central': [
    'Cape Coast Teaching Hospital',
    'Winneba Government Hospital',
    'Swedru Government Hospital',
    'Saltpond Government Hospital',
    'Abura Dunkwa Government Hospital',
    'Twifo Praso Hospital',
    'Assin Foso Hospital',
    'Mankessim Hospital',
    'Apam Hospital',
    'Kasoa Hospital',
    'Budumburam Hospital',
  ],
  'Eastern': [
    'Koforidua Government Hospital',
    'Tafo Government Hospital (East)',
    'Akwatia Government Hospital',
    'Nkawkaw Government Hospital',
    'Asamankese Government Hospital',
    'Kibi Government Hospital',
    'Mpraeso Government Hospital',
    'Akuse Government Hospital',
    'Somanya Government Hospital',
    'New Tafo Government Hospital',
    'Oda Government Hospital',
    'Suhum Government Hospital',
    'St. Joseph\'s Hospital (Koforidua)',
  ],
  'Volta': [
    'Ho Teaching Hospital',
    'Hohoe Government Hospital',
    'Keta Government Hospital',
    'Akatsi Government Hospital',
    'Kpando Government Hospital',
    'Sogakope Government Hospital',
    'Battor Government Hospital',
    'Anloga Hospital',
    'Amedzofe Hospital',
  ],
  'Northern': [
    'Tamale Teaching Hospital',
    'Tamale Central Hospital',
    'Savelugu Government Hospital',
    'Yendi Government Hospital',
    'Bimbilla Government Hospital',
    'Karaga Government Hospital',
    'Zabzugu Government Hospital',
    'Saboba Government Hospital',
    'Kpandai Government Hospital',
    'Gushegu Hospital',
    'Tatale Hospital',
  ],
  'Upper East': [
    'Bolgatanga Regional Hospital',
    'Navrongo Government Hospital',
    'Bawku Government Hospital',
    'Zebilla Hospital',
    'Sandema Government Hospital',
    'Chiana Hospital',
    'Paga Hospital',
    'Tempane Hospital',
    'Garu Hospital',
    'Builsa Hospital (Fumbisi)',
  ],
  'Upper West': [
    'Wa Regional Hospital',
    'Nandom Government Hospital',
    'Lawra Government Hospital',
    'Jirapa Government Hospital',
    'Lambussie Hospital',
    'Tumu Hospital',
    'Gurungu Hospital',
    'Wechiau Hospital',
    'Busie Hospital',
  ],
  'Bono': [
    'Sunyani Teaching Hospital',
    'Berekum Government Hospital',
    'Dormaa Ahenkro Government Hospital',
    'Nkoranza Hospital',
    'Atebubu Hospital',
    'Kintampo Hospital',
    'Nsoatre Hospital',
    'Fiapre Hospital',
  ],
  'Bono East': [
    'Techiman Municipal Hospital',
    'Kintampo Government Hospital',
    'Atebubu Government Hospital',
    'Prang Hospital',
    'Jema Hospital',
    'Nkoranza Hospital (East)',
    'Yeji Hospital',
  ],
  'Ahafo': [
    'Goaso Government Hospital',
    'Mim Hospital',
    'Hwidiem Hospital',
    'Kenyasi Hospital',
    'Ahenkro Hospital',
  ],
  'Western North': [
    'Sefwi Wiawso Government Hospital',
    'Sefwi Enchi Hospital',
    'Sefwi Asafo Hospital',
    'Akontombra Hospital',
    'Bibiani Government Hospital',
  ],
  'Oti': [
    'Dambai Government Hospital',
    'Kete Krachi Government Hospital',
    'Jasikan Government Hospital',
    'Nkwanta Government Hospital',
    'Worawora Hospital',
  ],
  'Savannah': [
    'Damongo Government Hospital',
    'Bole Government Hospital',
    'Sawla-Tuna-Kalba Hospital',
    'Salaga Government Hospital',
    'Fulfulso Hospital',
  ],
  'North East': [
    'Nalerigu Government Hospital',
    'Walewale Government Hospital',
    'Gambaga Hospital',
    'Chereponi Hospital',
    'Bunkpurugu Hospital',
  ],
}

export const GHANA_REGIONS = Object.keys(HOSPITALS_BY_REGION)

export const getHospitalsForRegion = (region) => {
  return HOSPITALS_BY_REGION[region] || HOSPITALS_BY_REGION['Ashanti'] || []
}